[package]
name = "viewwright-egui"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
egui.workspace = true
viewwright-model = { path = "../viewwright-model" }
viewwright-layout = { path = "../viewwright-layout" }

[dev-dependencies]
viewwright-compare = { path = "../viewwright-compare" }
viewwright-expectation = { path = "../viewwright-expectation" }
viewwitness = { git = "https://github.com/sguzman/viewwitness", rev = "f1930ab2a70175c46d12dd1e61501c3b4ae09408", default-features = false, features = ["egui"] }
